eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
feign:
  client:
    config:
      default:
        readTimeout: '5000'
        loggerLevel: FULL
    methods:
      name: cardtype
      uri: /api/cardType
      post: /get-cardtype

server:
  port: 8040
  
spring:
  application:
    name: cliente