eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
server:
  port: 8860

spring:
 application:
  name: cardType
  
feign:
  client:
    config:
      default:
        connectTimeout: '5000'
        readTimeout: '5000'